### ISSUE TITLE
Migrate to nodejs 4 [was: Failed to intialize database]

### ISSUE THREAD

**Issue by nlamirault** [pgrange/risno#30]
``` bash
$ cd slurp
$ make compile
$ node fetch_sites aquitaine
CTION NEEDED: require('iconv-lite').extendNodeEncodings() is not supported in your version of Node
See more info at https://github.com/ashtuchkin/iconv-lite/wiki/Node-v4-compatibility
 [_] fetching page 1 of paru-vendu
 [_] fetching page 2 of paru-vendu
 [_] fetching page 3 of paru-vendu
 [_] fetching page 4 of paru-vendu
 [_] fetching page 5 of paru-vendu
 [_] fetching page 6 of paru-vendu
 [_] fetching page 7 of paru-vendu
 [_] fetching page 8 of paru-vendu
 [_] fetching page 9 of paru-vendu
 [_] fetching page 10 of paru-vendu
 [_] fetching page 1 of a-vendre-a-louer
 [_] fetching page 2 of a-vendre-a-louer
 [_] fetching page 3 of a-vendre-a-louer
 [_] fetching page 4 of a-vendre-a-louer
 [_] fetching page 5 of a-vendre-a-louer
 [_] fetching page 6 of a-vendre-a-louer
 [_] fetching page 7 of a-vendre-a-louer
 [_] fetching page 8 of a-vendre-a-louer
 [_] fetching page 9 of a-vendre-a-louer
 [_] fetching page 10 of a-vendre-a-louer
 [_] fetching page 1 of annonces-jaunes
 [_] fetching page 2 of annonces-jaunes
 [_] fetching page 3 of annonces-jaunes
 [_] fetching page 4 of annonces-jaunes
 [_] fetching page 5 of annonces-jaunes
 [_] fetching page 6 of annonces-jaunes
 [_] fetching page 7 of annonces-jaunes
 [_] fetching page 8 of annonces-jaunes
 [_] fetching page 9 of annonces-jaunes
 [_] fetching page 10 of annonces-jaunes
 [_] fetching page 1 of immo-street
 [_] fetching page 2 of immo-street
 [_] fetching page 3 of immo-street
 [_] fetching page 4 of immo-street
 [_] fetching page 5 of immo-street
 [_] fetching page 6 of immo-street
 [_] fetching page 7 of immo-street
 [_] fetching page 8 of immo-street
 [_] fetching page 9 of immo-street
 [_] fetching page 10 of immo-street
 [_] fetching page 1 of belle-immobilier
 [_] fetching page 2 of belle-immobilier
 [_] fetching page 3 of belle-immobilier
 [_] fetching page 4 of belle-immobilier
 [_] fetching page 5 of belle-immobilier
 [_] fetching page 6 of belle-immobilier
 [_] fetching page 7 of belle-immobilier
 [_] fetching page 8 of belle-immobilier
 [_] fetching page 9 of belle-immobilier
 [_] fetching page 10 of belle-immobilier
 [_] fetching page 1 of se-loger
 [_] fetching page 2 of se-loger
 [_] fetching page 3 of se-loger
 [_] fetching page 4 of se-loger
 [_] fetching page 5 of se-loger
 [_] fetching page 6 of se-loger
 [_] fetching page 7 of se-loger
 [_] fetching page 8 of se-loger
 [_] fetching page 9 of se-loger
 [_] fetching page 10 of se-loger
 [_] fetching page 1 of sud-ouest
 [_] fetching page 2 of sud-ouest
 [_] fetching page 3 of sud-ouest
 [_] fetching page 4 of sud-ouest
 [_] fetching page 5 of sud-ouest
 [_] fetching page 6 of sud-ouest
 [_] fetching page 7 of sud-ouest
 [_] fetching page 8 of sud-ouest
 [_] fetching page 9 of sud-ouest
 [_] fetching page 10 of sud-ouest
Error: Unknown encoding: latin1
    at assertEncoding (string_decoder.js:9:11)
    at new exports.StringDecoder (string_decoder.js:23:3)
    at IncomingMessage.Readable.setEncoding (_stream_readable.js:188:33)
    at Request.onRequestResponse (/home/nlamirault/Perso/risno/slurp/node_modules/request/request.js:983:25)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by pgrange** [comment]
Quelle version de nodejs est-ce que tu utilises ?

**Comment by nlamirault** [comment]
```bash
$ node --version
v4.1.1
```

**Comment by pgrange** [comment]
See https://github.com/ashtuchkin/iconv-lite/commit/85938dbcb46ed9c98d712c363380fe41b7613c73

+    // Node authors rewrote Buffer internals to make it compatible with
+    // Uint8Array and we cannot patch key functions since then.

**Comment by pgrange** [comment]
Seems migrating to nodejs v4 will not be a piece of cake right now.

Could you use a previous version for your tests. I keep this issue open to deal with the migration but will deal with it later.
